version: "3.9"


services:
  web:
    build: .
    command: python /site/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/site
    ports:
      - 8000:8000
    depends_on:
      - db


  db:
    image: postgres
    container_name: db
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: site_django
      POSTGRES_USER: django_user
      POSTGRES_PASSWORD: ALD;GFHSODAVVJ[AIJ[]HNOIAVSNHD]
