# Generated by Django 4.2.3 on 2023-10-27 11:02

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='order',
            field=models.FloatField(default=resume.models.get_next_order),
        ),
    ]
