# Generated by Django 4.2.3 on 2023-10-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_skilltype_skill_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='experiences', to='resume.skill'),
        ),
    ]
