# Generated by Django 4.2.3 on 2023-10-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_experience_skills'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['type__order', 'order']},
        ),
        migrations.AddField(
            model_name='skilltype',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
