# Generated by Django 4.2.3 on 2023-10-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_skill_options_skilltype_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skilltype',
            options={'ordering': ['order']},
        ),
    ]
