# Generated by Django 4.2.3 on 2023-10-27 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_alter_skilltype_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
