# Generated by Django 4.2.3 on 2023-10-28 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_description_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=20)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resume.experience')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
