# Generated by Django 4.2.3 on 2023-10-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['work__start_date', 'id']},
        ),
    ]
